# Generated by Django 4.0.1 on 2022-01-26 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batiment_nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu_nom', models.CharField(max_length=50)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theapp.batiment')),
            ],
        ),
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macaddress', models.CharField(max_length=32)),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theapp.lieu')),
            ],
        ),
    ]
