# Generated by Django 4.0.1 on 2022-02-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quand', models.DateField()),
                ('ville', models.CharField(max_length=32)),
                ('couleur', models.CharField(max_length=7)),
            ],
        ),
    ]
