# Generated by Django 4.0.1 on 2022-02-04 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0002_atmo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmo',
            name='code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
