# Generated by Django 4.0.3 on 2022-03-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0003_atmo_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='adimaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('idd', models.IntegerField(default=0.0)),
                ('temp', models.IntegerField(default=0.0)),
                ('hum', models.IntegerField(default=0.0)),
                ('pres', models.IntegerField(default=0.0)),
                ('lum', models.IntegerField(default=0.0)),
                ('bruit', models.IntegerField(default=0.0)),
            ],
        ),
    ]
