# Generated by Django 4.0.3 on 2022-03-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0004_adimaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adimaker',
            name='day',
        ),
        migrations.AlterField(
            model_name='adimaker',
            name='idd',
            field=models.CharField(max_length=100),
        ),
    ]
